#import <DOM/EventTarget.idl>
#import <DOM/EventHandler.idl>
#import <Fetch/Request.idl>

// https://html.spec.whatwg.org/multipage/workers.html#worker
[Exposed=(Window,DedicatedWorker,SharedWorker), UseNewAKString]
interface Worker : EventTarget {
    constructor(DOMString scriptURL, optional WorkerOptions options = {});

    undefined terminate();
    undefined postMessage(any message, optional any transfer);

    attribute EventHandler onmessage;
    attribute EventHandler onmessageerror;
};

dictionary WorkerOptions {
    WorkerType type = "classic";
    RequestCredentials credentials = "same-origin";
    DOMString name = "";
};

enum WorkerType { "classic", "module" };
